### testing 'hello world'
GET http://localhost:3000/api

### testing create game
POST http://localhost:3000/api/games
Content-Type: application/json

{
    "name": "Wingspan",
    "creator": "Elizabeth Hargrave",
    "plays": 23
}

### testing get game lists
GET http://localhost:3000/api/games

### testing get game by id
GET http://localhost:3000/api/games/faf38e0a-3565-48b1-b5c7-7a5beb5e2411
